name: Django CI

on:
  push:
    branches: [ main, modulo20-github-actions ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: bookstore_user
          POSTGRES_PASSWORD: bookstore_pass
          POSTGRES_DB: bookstore_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U bookstore_user -d bookstore_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:
          DATABASE_URL: postgres://bookstore_user:bookstore_pass@localhost:5432/bookstore_db
        run: |
          python manage.py migrate

      - name: Run tests
        env:
          DATABASE_URL: postgres://bookstore_user:bookstore_pass@localhost:5432/bookstore_db
        run: |
          python manage.py test
